name: Run Node Script

on:
workflow_dispatch:
schedule:
- cron: '0    ' # 每小时执行一次，可改

jobs:
run-script:
runs-on: ubuntu-latest

steps:
- name: Checkout
uses: actions/checkout@v4

- name: Setup Node
uses: actions/setup-node@v4
with:
node-version: 20

- name: Run script
run: node m3u8_probe.node.js
